server:
  port: 8083

spring:
  application:
    name: feed-service
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms
  redis:
    connect-timeout: 2000ms
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: feed-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers

resilience4j:
  circuitbreaker:
    instances:
      post-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
      user-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
      follow-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
