server:
  port: 8083

spring:
  application:
    name: feed-service
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms
  redis:
    connect-timeout: 2000ms
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: feed-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
